import Head from 'next/head'
import Hero from '../components/Hero'
import Layout from '../components/Layout'
import { useSession } from 'next-auth/react'
import { useEffect, useState } from 'react'

export default function Home() {
  const { data: session, status } = useSession()

  const [userId, setUserId] = useState(null)

  useEffect(() => {
    console.log('ini session', session)

    //@ts-ignore
    setUserId(session?.user.id)
    // console.log(userId)

    async function fetchRepo() {
      if (status === 'loading') return <p className="text-white">Loading...</p>
      if (session) {
        try {
          // await fetch('/api/github/repos', {
          //   method: 'POST',
          //   headers: {
          //     Accept: 'application/json',
          //     'Content-Type': 'application/json',
          //   },
          //   body: JSON.stringify({
          //     // @ts-ignore
          //     id: userId,
          //   }),
          // })
          const afterData = await fetch('/api/github/repos').then((res) =>
            res.json()
          )
          console.log('after data:', afterData)
        } catch (e) {
          console.error(e)
        }
      }
    }
    fetchRepo()
  }, [session, status])

  return (
    <div>
      <Head>
        <title>Github Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/github_icon.png" />
      </Head>
      <main>
        <Layout>
          <Hero />
        </Layout>
      </main>
    </div>
  )
}
